config:
  ignore:
    - "README.md"
    - ".ticonfig.yaml"
    - "**/*.md"
    - "**/*.txt"
    - "**/*.html"
    - "**/*.xml"
    - "gradlewAll"
    - "config/kraft/README.md"
    - "**/*.properties"
    - "examples/README"
    - "**/*.py"
    - "**/*.sh"
    - "tests/docker/Dockerfile"
